<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="420299" started-at="2015-08-05T19:20:11Z" finished-at="2015-08-05T19:27:11Z">
    <groups>
      <group name="Sanity IOS">
        <method signature="SanityIos.loginSample()[pri:0, instance:Native.SanityIos@1838ccb8]" name="loginSample" class="Native.SanityIos"/>
      </group> <!-- Sanity IOS -->
    </groups>
    <test name="Sanity Tests" duration-ms="420299" started-at="2015-08-05T19:20:11Z" finished-at="2015-08-05T19:27:11Z">
      <class name="Native.SanityIos">
        <test-method status="PASS" signature="setupBeforeSuite(org.testng.ITestContext)[pri:0, instance:Native.SanityIos@1838ccb8]" name="setupBeforeSuite" is-config="true" duration-ms="87600" started-at="2015-08-05T22:18:43Z" finished-at="2015-08-05T22:20:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@68699afc]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupBeforeSuite -->
        <test-method status="PASS" signature="checkHomeScreen()[pri:0, instance:Native.SanityIos@1838ccb8]" name="checkHomeScreen" is-config="true" duration-ms="2169" started-at="2015-08-05T22:20:11Z" finished-at="2015-08-05T22:20:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkHomeScreen -->
        <test-method status="FAIL" signature="loginSample()[pri:0, instance:Native.SanityIos@1838ccb8]" name="loginSample" duration-ms="68113" started-at="2015-08-05T22:20:13Z" description="Test the login via the sample button" finished-at="2015-08-05T22:21:21Z">
          <exception class="com.applitools.eyes.NewTestException">
            <message>
              <![CDATA['Dashboard Tab' of 'iOS_SG'. Please approve the new baseline at https://eyes.applitools.com/app/sessions/251963498330947]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.applitools.eyes.NewTestException: 'Dashboard Tab' of 'iOS_SG'. Please approve the new baseline at https://eyes.applitools.com/app/sessions/251963498330947
	at com.applitools.eyes.EyesBase.close(EyesBase.java:521)
	at com.applitools.eyes.Eyes.close(Eyes.java:22)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:444)
	at com.applitools.eyes.Eyes.close(Eyes.java:22)
	at Native.IosMethods.eyesCheckWindow(IosMethods.java:73)
	at Native.SanityIos.loginSample(SanityIos.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- com.applitools.eyes.NewTestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginSample -->
        <test-method status="PASS" signature="checkHomeScreen()[pri:0, instance:Native.SanityIos@1838ccb8]" name="checkHomeScreen" is-config="true" duration-ms="96983" started-at="2015-08-05T22:21:21Z" finished-at="2015-08-05T22:22:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkHomeScreen -->
        <test-method status="FAIL" signature="loginSample()[pri:0, instance:Native.SanityIos@1838ccb8]" name="loginSample" duration-ms="73652" started-at="2015-08-05T22:22:58Z" description="Test the login via the sample button" finished-at="2015-08-05T22:24:12Z">
          <exception class="com.applitools.eyes.TestFailedException">
            <message>
              <![CDATA['Dashboard Tab' of 'iOS_SG'. See details at https://eyes.applitools.com/app/sessions/251963498169580]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.applitools.eyes.TestFailedException: 'Dashboard Tab' of 'iOS_SG'. See details at https://eyes.applitools.com/app/sessions/251963498169580
	at com.applitools.eyes.EyesBase.close(EyesBase.java:504)
	at com.applitools.eyes.Eyes.close(Eyes.java:22)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:444)
	at com.applitools.eyes.Eyes.close(Eyes.java:22)
	at Native.IosMethods.eyesCheckWindow(IosMethods.java:73)
	at Native.SanityIos.loginSample(SanityIos.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- com.applitools.eyes.TestFailedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginSample -->
        <test-method status="PASS" signature="checkHomeScreen()[pri:0, instance:Native.SanityIos@1838ccb8]" name="checkHomeScreen" is-config="true" duration-ms="96606" started-at="2015-08-05T22:24:12Z" finished-at="2015-08-05T22:25:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkHomeScreen -->
        <test-method status="FAIL" signature="loginSample()[pri:0, instance:Native.SanityIos@1838ccb8]" name="loginSample" duration-ms="82748" started-at="2015-08-05T22:25:48Z" description="Test the login via the sample button" finished-at="2015-08-05T22:27:11Z">
          <exception class="com.applitools.eyes.NewTestException">
            <message>
              <![CDATA['World wide orders Tab' of 'iOS_SG'. Please approve the new baseline at https://eyes.applitools.com/app/sessions/251963497980645]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.applitools.eyes.NewTestException: 'World wide orders Tab' of 'iOS_SG'. Please approve the new baseline at https://eyes.applitools.com/app/sessions/251963497980645
	at com.applitools.eyes.EyesBase.close(EyesBase.java:521)
	at com.applitools.eyes.Eyes.close(Eyes.java:22)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:444)
	at com.applitools.eyes.Eyes.close(Eyes.java:22)
	at Native.IosMethods.eyesCheckWindow(IosMethods.java:73)
	at Native.SanityIos.loginSample(SanityIos.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- com.applitools.eyes.NewTestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginSample -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Native.SanityIos@1838ccb8]" name="tearDown" is-config="true" duration-ms="4572" started-at="2015-08-05T22:27:11Z" finished-at="2015-08-05T22:27:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Native.SanityIos -->
    </test> <!-- Sanity Tests -->
  </suite> <!-- Suite -->
</testng-results>
