<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SGMacBookPROs-MacBook-Pro.local" name="Native.SanityIos" tests="3" failures="0" timestamp="19 Jul 2015 08:48:42 GMT" time="2119.602" errors="3">
  <testcase name="loginSample" time="680.258" classname="Native.SanityIos">
    <error type="com.applitools.eyes.TestFailedException" message="&#039;SampleApp Service Calls - See All (Mall of America&#039; of &#039;iOS_SG&#039;. See details at https://eyes.applitools.com/app/sessions/251965006648197">
      <![CDATA[com.applitools.eyes.TestFailedException: 'SampleApp Service Calls - See All (Mall of America' of 'iOS_SG'. See details at https://eyes.applitools.com/app/sessions/251965006648197
	at com.applitools.eyes.EyesBase.close(EyesBase.java:504)
	at com.applitools.eyes.Eyes.close(Eyes.java:22)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:444)
	at com.applitools.eyes.Eyes.close(Eyes.java:22)
	at Native.IosMethods.eyesCheckWindow(IosMethods.java:75)
	at Native.SanityIos.loginSample(SanityIos.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- loginSample -->
  <testcase name="loginSample" time="866.400" classname="Native.SanityIos">
    <error type="com.applitools.eyes.TestFailedException" message="&#039;SampleApp Service Calls- priority = 4&#039; of &#039;iOS_SG&#039;. See details at https://eyes.applitools.com/app/sessions/251965005106061">
      <![CDATA[com.applitools.eyes.TestFailedException: 'SampleApp Service Calls- priority = 4' of 'iOS_SG'. See details at https://eyes.applitools.com/app/sessions/251965005106061
	at com.applitools.eyes.EyesBase.close(EyesBase.java:504)
	at com.applitools.eyes.Eyes.close(Eyes.java:22)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:444)
	at com.applitools.eyes.Eyes.close(Eyes.java:22)
	at Native.IosMethods.eyesCheckWindow(IosMethods.java:75)
	at Native.SanityIos.loginSample(SanityIos.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- loginSample -->
  <testcase name="loginSample" time="572.944" classname="Native.SanityIos">
    <error type="com.applitools.eyes.TestFailedException" message="&#039;SampleApp Service Calls - See All (Mall of America&#039; of &#039;iOS_SG&#039;. See details at https://eyes.applitools.com/app/sessions/251965005975778">
      <![CDATA[com.applitools.eyes.TestFailedException: 'SampleApp Service Calls - See All (Mall of America' of 'iOS_SG'. See details at https://eyes.applitools.com/app/sessions/251965005975778
	at com.applitools.eyes.EyesBase.close(EyesBase.java:504)
	at com.applitools.eyes.Eyes.close(Eyes.java:22)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:444)
	at com.applitools.eyes.Eyes.close(Eyes.java:22)
	at Native.IosMethods.eyesCheckWindow(IosMethods.java:75)
	at Native.SanityIos.loginSample(SanityIos.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- loginSample -->
</testsuite> <!-- Native.SanityIos -->
